name: Most Used Languages
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_aliases: javascript:JS typescript:TS
