name: WakaTime
on:
  schedule: [{cron: "0 0 * * 1"}]
  push: {branches: ["master", "main"]}
jobs:
  wakatime: 
    runs-on: ubuntu-latest
    steps:
     - uses: lowlighter/metrics@latest
       with:
        filename: metrics.plugin.wakatime.svg
        token: NOT_NEEDED
        base: ""
        plugin_wakatime: yes
        plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
